name: app_usage
description: App usage plugin for Android only
version: 1.1.1
homepage: https://github.com/cph-cachet/flutter-plugins/blob/master/packages/app_usage

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: dk.cachet.app_usage
        pluginClass: AppUsagePlugin
      ios:
        pluginClass: AppUsagePlugin

