name: carp_background_location
description: A location plugin that works in the background. Supports Android and iOS
version: 1.0.2+1
homepage: https://github.com/cph-cachet/flutter-plugins
author:  CACHET Team <cph.cachet@gmail.com>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_locator: ^1.2.2
  location_permissions: ^3.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

